-- Création des rôles
CREATE ROLE C##ROLE_ADMIN;
CREATE ROLE C##ROLE_GESTIONNAIRE;
CREATE ROLE C##ROLE_COMPTABLE;

-- Attribution des privilèges de session
GRANT CREATE SESSION TO C##ROLE_ADMIN, C##ROLE_GESTIONNAIRE, C##ROLE_COMPTABLE;

-- ADMIN : Tous les privilèges sur les tables principales
GRANT ALL PRIVILEGES ON UTILISATEUR TO C##ROLE_ADMIN;
GRANT ALL PRIVILEGES ON CLIENT TO C##ROLE_ADMIN;
GRANT ALL PRIVILEGES ON PRODUIT TO C##ROLE_ADMIN;
GRANT ALL PRIVILEGES ON COMMANDE TO C##ROLE_ADMIN;
GRANT ALL PRIVILEGES ON LIGNE_COMMANDE TO C##ROLE_ADMIN;
GRANT ALL PRIVILEGES ON PAIEMENT TO C##ROLE_ADMIN;
GRANT ALL PRIVILEGES ON STOCK_MOUVEMENT TO C##ROLE_ADMIN;
GRANT ALL PRIVILEGES ON AUDIT_LOG TO C##ROLE_ADMIN;

-- GESTIONNAIRE : CRUD sur clients, produits, commandes
GRANT SELECT, INSERT, UPDATE ON CLIENT TO C##ROLE_GESTIONNAIRE;
GRANT SELECT, INSERT, UPDATE ON PRODUIT TO C##ROLE_GESTIONNAIRE;
GRANT SELECT, INSERT, UPDATE ON COMMANDE TO C##ROLE_GESTIONNAIRE;
GRANT SELECT, INSERT, UPDATE ON LIGNE_COMMANDE TO C##ROLE_GESTIONNAIRE;
GRANT SELECT, INSERT, UPDATE ON STOCK_MOUVEMENT TO C##ROLE_GESTIONNAIRE;

-- COMPTABLE : Lecture commandes + gestion paiements
GRANT SELECT ON COMMANDE TO C##ROLE_COMPTABLE;
GRANT SELECT ON CLIENT TO C##ROLE_COMPTABLE;
GRANT SELECT, INSERT, UPDATE ON PAIEMENT TO C##ROLE_COMPTABLE;

-- Création des utilisateurs
CREATE USER C##ADMIN_ERP IDENTIFIED BY "Admin123!";
CREATE USER C##GEST_ERP IDENTIFIED BY "Gest123!";
CREATE USER C##COMPTABLE_ERP IDENTIFIED BY "Compta123!";

-- Attribution des rôles aux utilisateurs
GRANT C##ROLE_ADMIN TO C##ADMIN_ERP;
GRANT C##ROLE_GESTIONNAIRE TO C##GEST_ERP;
GRANT C##ROLE_COMPTABLE TO C##COMPTABLE_ERP;
