CREATE SEQUENCE seq_utilisateur START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_client START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_produit START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_commande START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_ligne START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_paiement START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_mouvement START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_audit START WITH 1 INCREMENT BY 1;