-- Configuration de la sauvegarde
CONFIGURE RETENTION POLICY TO RECOVERY WINDOW OF 7 DAYS;
CONFIGURE CONTROLFILE AUTOBACKUP ON;

-- Sauvegarde complète
BACKUP DATABASE PLUS ARCHIVELOG;

-- Sauvegarde incrémentielle
BACKUP INCREMENTAL LEVEL 1 DATABASE PLUS ARCHIVELOG;